version: '3.9'

services:
  db:
    image: postgres:14-alpine
    container_name: touragency-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=dev
      - POSTGRES_DB=touragency
